### ISSUE TITLE
Other encodings

### ISSUE THREAD

**Issue by kwea123** [ankurhanda/nerf2D#1]
Thanks for the experiments showing the effectiveness of the gamma encoding!
As you mentioned in the readme, there are also other encodings such as RBF.

Did you experiment with other encodings? What is the best performing one in terms of PSNR/number of parameters?

**Comment by Luciennnnnnn** [comment]
> Thanks for the experiments showing the effectiveness of the gamma encoding!
> As you mentioned in the readme, there are also other encodings such as RBF.
> 
> Did you experiment with other encodings? What is the best performing one in terms of PSNR/number of parameters?

Do you have any conclusion about this?
