### ISSUE TITLE
How can your method be extended to 3D point clouds?

### ISSUE THREAD

**Issue by longmalongma** [ankurhanda/nerf2D#2]
Hi, How can your positional encoding be extended to 3D point clouds?

**Comment by ankurhanda** [comment]
You can change the input to add sine / cosines of z coordinate too. The code only shows adding sine / cosines of x and y coordinates but it's pretty straightforward to add sine/cosines of z coordinate here and change the output to what you want if it is different from (r,g,b).

**Comment by longmalongma** [comment]
> You can change the input to add sine / cosines of z coordinate too. The code only shows adding sine / cosines of x and y coordinates but it's pretty straightforward to add sine/cosines of z coordinate here and change the output to what you want if it is different from (r,g,b).

Thanks for your reply, What is the purpose of your two lines? Why build an arithmetic list?
        x_linspace = (np.linspace(0, W-1, W)/W)*2 -1 
        y_linspace = (np.linspace(0, H-1, H)/H)*2 -1
