### ISSUE TITLE
Why build an arithmetic list?

### ISSUE THREAD

**Issue by longmalongma** [ankurhanda/nerf2D#3]
Thanks for your reply, What is the purpose of your two lines? Why build an arithmetic list?
x_linspace = (np.linspace(0, W-1, W)/W)*2 -1
y_linspace = (np.linspace(0, H-1, H)/H)*2 -1

**Comment by ankurhanda** [comment]
This is to normalise x and y to lie between [-1, 1]. 

The lines after Eq.(4) in the paper mention that too https://arxiv.org/pdf/2003.08934.pdf

**Comment by longmalongma** [comment]
> between

Thanks for your reply. Why do we need to normalize? What is the impact if the normalization operation is not used?

**Comment by longmalongma** [comment]
> This is to normalise x and y to lie between [-1, 1].
> 
> The lines after Eq.(4) in the paper mention that too https://arxiv.org/pdf/2003.08934.pdf

How to normalize tensor?
