### ISSUE TITLE
What the difference between Batch normalization and np.linspace?

### ISSUE THREAD

**Issue by longmalongma** [ankurhanda/nerf2D#5]
Is there any batch normalization operation in the network? Batch normalization (bn) operations can also be normalized. What is the difference between them? Why not use BN?

**Comment by ankurhanda** [comment]
Why don't you try it out by commenting out the normalisation and see what you get? I feel this is a very straightforward experiment that you can do it yourself. I am busy with other things so I won't be going back to it. 

Networks with few layers (< 5) didn't need BN. 

Thank you.
